# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bb4849fa236013de3aac94133dfe37e59623ef30e8d9f399f7f9c942f9609592db3829a797ed10c2e05bb91c55428205901e88c664bf2d67e98bc5c45649c1e

test:
  secret_key_base: 788889bca4d1c463a25cc2be1f9ff5d71c1df33e6628b2ac30fdf6710071a5c79f17e7e8c2055d10628a9449396d793ef5325d4d522decac9b73e2e0efc0d6de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
